language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t alvindecastro/react-test -f  ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alvindecastro/react-test npm test

after_success:
  - docker build -t alvindecastro/multi-client ./client
  - docker build -t alvindecastro/multi-nginx ./nginx
  - docker build -t alvindecastro/multi-server ./server
  - docker build -t alvindecastro/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push alvindecastro/multi-client
  - docker push alvindecastro/multi-nginx
  - docker push alvindecastro/multi-server
  - docker push alvindecastro/multi-worker